# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c05149a45c1d41c04a652c748bbcce3ff0838d31a939d7fddcef7347461abbaa557911d66c82465d3f8953add5d8b5e8d29d213b0b07f683845356f74b8db4e

test:
  secret_key_base: c5a4564ac83a214d1e99b74dceb9ede28356a2b97d605d8ae6b6df3c156f60636026f08d91e57e930e41911ec17cdee3ed0752761635021751e5c4b0096d1502

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
